ceph:
  admin:
    endpoint: http://172.20.116.155:7480/admin
    access-key: ICEK2OLI1B0VQ09R5RHG
    secret-key: XIWpFZuf3IRW7j1O2OAhMTN5MSMFoecYYu2bcRmI
spring:
  datasource:
    url: jdbc:mysql://172.20.116.155:3306/ceph?serverTimezone=GMT%2B8
    username: ceph
    password: 12qw!@QW
mybatis:
  mapper-locations: classpath:mybatis/**/*.xml

logging:
  level:
    io.cat.ceph.dao: debug
    io.cat.ceph.dao.CephUserDAO.getCephUserByName: error
    io.cat.ceph.dao.CephUserDAO.getAll: error